In [1]:
import numpy as np

In [5]:
arr=np.array([12,23,45,56,32])

In [7]:
arr

array([12, 23, 45, 56, 32])

In [9]:
print(arr)

[12 23 45 56 32]


In [11]:
type(arr)

numpy.ndarray

In [13]:
arr.dtype

dtype('int32')

In [73]:
arr=np.array([12,23,45,56,66.22])

In [17]:
arr.dtype

dtype('float64')

In [29]:
%%timeit
arr=np.array([12,23,45,56,66.22,'pune'])

5.48 µs ± 354 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [30]:
arr.dtype

dtype('<U32')

In [31]:
arr

array(['12', '23', '45', '56', '66.22', 'pune'], dtype='<U32')

In [35]:
arr[3]

'56'

In [37]:
arr.shape

(6,)

In [43]:
arr=np.array([12,23,45,56,66])

In [45]:
arr * 2   # here multiply 2 

array([ 24,  46,  90, 112, 132])

In [47]:
np.arange(12)  # create array elements from 1 to 11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [49]:
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [55]:
np.arange(-5,5,2.5)  # in range function there is no given float value

array([-5. , -2.5,  0. ,  2.5])

In [57]:
np.zeros(10)   # only applicable for zero and ones  special method

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [59]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [61]:
# 2d array

In [75]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [65]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
arr1.shape

(3, 3)

In [71]:
arr1.ndim   # to check the dimention of array

2

In [77]:
arr1.flatten()  #to convert the any dimention array in to one dimention

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
arr1.shape

(3, 3)

In [85]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [87]:
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [89]:
arr1.shape

(4, 3)

In [91]:
arr1.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [93]:
arr1.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [95]:
arr1.reshape(6,-1)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [103]:
arr1.reshape(4,3,-1)

array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]]])

In [105]:
arr1.shape(3,2,2)

TypeError: 'tuple' object is not callable

In [107]:
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [109]:
arr1[0:3,0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [111]:
arr=np.array([1,3,5,6,3,3,1,7])

In [113]:
np.unique(arr)

array([1, 3, 5, 6, 7])

In [119]:
arr.mean()

3.625

In [133]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [129]:
np.linalg.det(arr1)

6.66133814775094e-16

In [131]:
np.linalg.inv(arr1)

array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
       [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
       [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

In [135]:
arr2=np.array[[1

In [137]:
arr1 @ arr2

ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [ ]:
arr1 * arr2